### ISSUE TITLE
OS X and Elgato streamdeck

### ISSUE THREAD

**Issue by mccordgh** [OpenMacroBoard/OpenMacroBoard.SDK#4]
Hi, there! You have some great libraries for the Elgato StreamDeck on Windows.

I am wondering about Mac Support, or if you could point me in the right direction to get something going myself in C# to be able to interact with the StreamDeck (not by making a plugin). I'm trying to make a game for a game jam with the StreamDeck, and hoping to be able to bring something in to use in Unity with C#. Im on OS X.

**Comment by wischi-chr** [comment]
Hi. Sure.

You could use the node implamentation (https://github.com/Lange/node-elgato-stream-deck) according to the readme it supports macOS.

If you want to write something in C# you would need a library to communicate to hid devices (with a quick google search I found [Device.NET](https://github.com/MelbourneDeveloper/Device.Net) and [HidSharp](https://www.nuget.org/packages/HidSharp/) but I've no way of testing them.

After that you just need to send the correct payload to the library.
You can browse this library to find out what you need to send, you could for example start with this files:

- [StreamDeckHardwareInfo.cs](https://github.com/OpenMacroBoard/StreamDeckSharp/blob/master/src/StreamDeckSharp/Internals/StreamDeckHardwareInfo.cs)
- [StreamDeckMiniHardwareInfo.cs](https://github.com/OpenMacroBoard/StreamDeckSharp/blob/master/src/StreamDeckSharp/Internals/StreamDeckMiniHardwareInfo.cs)
- [BasicHidClient.cs](https://github.com/OpenMacroBoard/StreamDeckSharp/blob/master/src/StreamDeckSharp/Internals/BasicHidClient.cs)

Let me know if you need something.

**Comment by mccordgh** [comment]
Thanks for the reply! I will try and hack on this during this week / weekend on my mac :)

**Comment by david-sharer** [comment]
Hi! I'm working on this now w/ @mccordgh.

We managed to find the device on both windows + mac using a combination of Device.Net/Usb.Net, Hid.Net, and Device.Net.LibUsb. I'll try to get the payloads working sometime in the next few days.

Would you be open to a PR that converts this to using .NET Core/Standard instead of Framework? I'm not 100% that all the current dependencies would work, though.

(I deleted and reposted this because apparently it doesn't produce notifications when you're "flagged"?)

**Comment by wischi-chr** [comment]
yea I'm open for PRs but it should still be possible to build the core stuff with .NET 4 (so you'd probably need a shared project because .NET 4.0 does not implement any .net standard.

**Comment by wischi-chr** [comment]
Dropped .NET 4 support, switched to HidSharp and netstandard2. I'm not a Mac user, so I can't test it but it should work now (I guess).

**Comment by chriskooken** [comment]
Has anyone been able to get this to work? I am running this on Xamarin.Mac and getting this error:

`System.TypeInitializationException: The type initializer for 'StreamDeckSharp.Hardware' threw an exception. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.`
