### ISSUE TITLE
Deckboard Support?

### ISSUE THREAD

**Issue by shep2** [OpenMacroBoard/OpenMacroBoard.SDK#7]
Any chance you will update this to have support for deckboard's virtual deck? https://deckboard.app/  It seems to be a reasonable freeware clone to StreamDeck. Teaching classes this fall and this would be nice to have for added powerpoint support and other things.

**Comment by wischi-chr** [comment]
It depends on what you are trying to do. You could already control power point using deckboard.app
Open Macro Board is "just" a library and not a finished product. I took a look at deckboard and it would be doable to implement the socket.io protocol for OpenMacroBoard but it wouldn't help you controlling powerpoint
